// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9TmEc3-wlJneE3b90vVoabuEqP_YTFCE',
    appId: '1:978039550520:web:11d01e4db2459023ec2ccd',
    messagingSenderId: '978039550520',
    projectId: 'fityouapp-b1c87',
    authDomain: 'fityouapp-b1c87.firebaseapp.com',
    storageBucket: 'fityouapp-b1c87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Gy1fxbdNYYRSkofeEVuFl3-nW5cwwbo',
    appId: '1:978039550520:android:d5f8b551b243453bec2ccd',
    messagingSenderId: '978039550520',
    projectId: 'fityouapp-b1c87',
    storageBucket: 'fityouapp-b1c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApIIhcGXND0P-lFUaRKCHyW26BDDvV2N8',
    appId: '1:978039550520:ios:376d8832b144325eec2ccd',
    messagingSenderId: '978039550520',
    projectId: 'fityouapp-b1c87',
    storageBucket: 'fityouapp-b1c87.firebasestorage.app',
    iosBundleId: 'com.bytebrigade.fitnessApp',
  );
}
